spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev         #开发环境
  application:
    name: micloud-config-client
eureka:
  client:
    #server-url:
    serviceUrl: 
      defaultZone: http://eureka.7001.com:7001/eureka/
      #defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/,http://eureka.7003.com:7003/eureka/
---
server:
  port: 8202
spring:
  profiles: test         #开发环境
  application:
    name: micloud-config-client
eureka:
  client:
    #server-url:
    serviceUrl: 
      defaultZone: http://eureka.7001.com:7001/eureka/
      #defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/,http://eureka.7003.com:7003/eureka/
# 请保存为UTF-8格式